server:
  port: 8080
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka 

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  boot:
    admin:
      client:
        url: http://localhost:8081
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: myapp
          client-secret: 123
          introspection-uri: http://localhost:50375/oauth/check_token
                
  cloud:
    gateway:
      routes:
      - id: costCalculation
        uri: lb://COST-CALCULATION
        predicates:
        - Path=/cost-calculation/**
      - id: mktplaceIntegration
        uri: lb://MKTPLACE-INTEGRATION
        predicates:
        - Path=/mktplace-integration/**
      - id: orders
        uri: lb://ORDERS
        predicates:
        - Path=/orders/**
      - id: sysadmin
        uri: lb://SYSADMIN
        predicates:
        - Path=/sysadmin/**
      - id: organizational
        uri: lb://ORGANIZATIONAL
        predicates:
        - Path=/organizational/**
      - id: oauth
        uri: lb://OAUTH
        predicates:
        - Path=/oauth/**

# actuator
#indica que health deve mostrar detalhes sempre
#alem do health e do info ele sempre vai export todos endpoints disponiveis
management:
  endpoint:
    health:
      show-details: always

#LOG level
logging:
 level:
   root: DEBUG
   org:  
    springframework:
      security: DEBUG
